### ISSUE TITLE
Apidya not in games.txt

### ISSUE THREAD

**Issue by wolfsoftgmbh** [amigavision/AmigaVision#231] opened 2024-12-27 17:35 UTC
As a user of Zaparoo (ex Tapto) I want to start Apidya via NFC Reader Card but there is no entry of the game in the games.txt :-(
Go on
Thanks

**Comment by limi** [comment] 2024-12-29 19:16
Duplicate of #204

**Closed by limi** 2024-12-29 19:16 UTC
